package Vista.VistaConsola;

public enum EstadoConsola {
    MENU_PRINCIPAL,
    MOSTRAR_INICIO,
    ESPERANDO_JUGADORES,
    TURNO_ACTUAL,
    OFRECER_CANTO,
    RESPUESTA_TERMINO,
    RESPUESTA_MENSAJE_ERROR,
    MOSTRANDO_RANKING_COMO_JUGAR,
    MOSTRANDO_RANKING_AL_FINALIZAR,
    RESPUESTA_PUNTAJE
}
