package Vista.VistaConsola;

public enum EstadoConsola {
    MENU_PRINCIPAL,
    MOSTRAR_INICIO,
    ESPERANDO_JUGADORES,
    TURNO_ACTUAL,
    OFRECER_CANTO,
    RESPUESTA_TERMINO,
    MOSTRANDO_RANKING_COMO_JUGAR,

}
