package Model;

public enum Eventos {
    COMENZAR_JUEGO,
    JUGADOR_AGREGADO,
    CARTAS_REPARTIDAS,
    ACTUALIZACION_TURNO,
    OFRECER_TUTE,
    OFRECER_LAS_40,
    OFRECER_LAS_20,
    MANO_TERMINADA,
    CARTA_ERRONEA,
    GANADOR_POR_TUTE,
    CANTA_LAS_40,
    CANTA_LAS_20,
    GANADOR_POR_PUNTOS,
    ULTIMAS_10,
    CARTA_TIRADA
}
