package Model;

public enum Eventos {//TODOS POR CAMBIOS DE ESTADO QUE NECESITA SABER EL CONTROLADOR
    COMENZAR_JUEGO,//COMIENZA EL JUEGO, EL PRIMER JUGADOR TIENE QUE TIRAR UNA CARTA
    JUGADOR_AGREGADO,//SE AGREGA UN JUGADOR AL ARRAYLIST DE JUGADORES
    CARTAS_REPARTIDAS,//SE AGREGAN LAS CARTAS AL MAZO DE CADA JUGADOR
    ACTUALIZACION_TURNO,//SE ACTUALIZA EL JUGADOR_ACTUAL
    MANO_TERMINADA,//SE LIMPIAN LAS CARTAS DE LA MESA (CARTAS_JUGADAS_EN_LA_MANO.ISEMPTY())
    GANADOR_POR_PUNTOS,//SE ESTABLECE EL GANADOR_FINAL
    ULTIMAS_10,//SE LE SUMAN 10 PUNTOS AL JUGADOR_ACTUAL Y CAMBIA EL ESTADO DE ESTADO_CANTO
    CARTA_TIRADA,//SE SUMA UNA CARTA AL ARRAYLIST DE CARTAS_JUGADAS_EN_LA_MANO
    OFRECER_LAS_20,//CAMBIA EL ESTADO DE ESTADO_CANTO
    CANTA_LAS_20,//SE SUMAN 20 PUNTOS AL JUGADOR ACTUAL
    OFRECER_LAS_40,//CAMBIA EL ESTADO DE ESTADO_CANTO
    CANTA_LAS_40,//SE SUMAN 40 PUNTOS AL JUGADOR ACTUAL
    OFRECER_TUTE,//CAMBIA EL ESTADO DE ESTADO_CANTO
    GANADOR_POR_TUTE,//SE ESTABLECE UN GANADOR_FINAL POR TUTE

}
