package Controlador;

public enum Estado_UI {//VER BIEN QUE ESTADOS VAN ACA
    NORMAL,
    ESPERANDO_OK_CANTO,
    ESPERANDO_OK_ULTIMAS_10,
    ESPERANDO_OK_PUNTAJES,
    ESPERANDO_RESPUESTA_TERMINO_JUEGO
}
